name: psychopyeeg
channels:
- conda-forge
dependencies:
- python=3.6
- psychopy
- mne
- pip
- pip:
  - ppc
  - psychtoolbox
  - pygame
  - pyo
  - pyparallel; platform_system != "Windows"
  - SoundFile; platform_system == "Windows"
  - triggers
  - websocket_client